# Generated by Django 5.1 on 2024-08-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
